ERROR - 2022-03-31 16:27:04 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: NO)
ERROR - 2022-03-31 16:27:04 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: NO)
CRITICAL - 2022-03-31 16:27:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
#0 C:\xampp\htdocs\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\app\Controllers\Controlador_Login.php(83): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Login->Iniciar_sesion()
#6 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Login))
#7 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-03-31 16:27:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
#0 C:\xampp\htdocs\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\app\Controllers\Controlador_Login.php(83): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Login->Iniciar_sesion()
#6 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Login))
#7 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-31 16:33:40 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: NO)
CRITICAL - 2022-03-31 16:33:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
#0 C:\xampp\htdocs\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\app\Controllers\Controlador_Login.php(83): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Login->Iniciar_sesion()
#6 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Login))
#7 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-31 16:49:02 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: NO)
CRITICAL - 2022-03-31 16:49:02 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
#0 C:\xampp\htdocs\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\app\Controllers\Controlador_Login.php(83): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Login->Iniciar_sesion()
#6 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Login))
#7 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-31 16:49:34 --> Error connecting to the database: Unknown database 'codeigniter'
CRITICAL - 2022-03-31 16:49:34 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'codeigniter'
#0 C:\xampp\htdocs\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\app\Controllers\Controlador_Login.php(83): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Login->Iniciar_sesion()
#6 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Login))
#7 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-31 16:50:04 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-31 16:50:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\app\Controllers\Controlador_Login.php(83): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Login->Iniciar_sesion()
#6 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Login))
#7 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-31 16:56:11 --> Table 'codeigniter.productos' doesn't exist
CRITICAL - 2022-03-31 16:56:11 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\app\Controllers\Controlador_Contenido.php(36): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Contenido->tablasDOM2()
#3 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Contenido))
#4 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-03-31 17:01:49 --> Table 'codeigniter.proveedor' doesn't exist
CRITICAL - 2022-03-31 17:01:49 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\app\Controllers\Controlador_Contenido.php(43): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Contenido->tablasDOM3()
#3 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Contenido))
#4 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-03-31 17:02:33 --> Table 'codeigniter.proveedor' doesn't exist
CRITICAL - 2022-03-31 17:02:33 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\app\Controllers\Controlador_Contenido.php(43): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Contenido->tablasDOM3()
#3 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Contenido))
#4 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-03-31 20:18:51 --> syntax error, unexpected end of file
#0 C:\xampp\htdocs\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\system\Common.php(1089): CodeIgniter\View\View->render('Contenido/Tabla...', Array, true)
#2 C:\xampp\htdocs\app\Controllers\Controlador_Contenido.php(31): view('Contenido/Tabla...', Array)
#3 C:\xampp\htdocs\system\CodeIgniter.php(825): App\Controllers\Controlador_Contenido->tablasDOM()
#4 C:\xampp\htdocs\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controlador_Contenido))
#5 C:\xampp\htdocs\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
